┏━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓ ┃ Best ┃ Epoch ┃ Trades ┃ Win  Draw  Loss  Win% ┃ Avg profit ┃ Profit ┃ Avg duration ┃ Objective ┃ Max Drawdown (Acct) ┃ ┡━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩ └──────┴───────┴────────┴───────────────────────┴────────────┴────────┴──────────────┴───────────┴─────────────────────┘ Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0/200   0% • 0:00:09 • -:--:-- 2025-06-11 07:04:37,727 - freqtrade - ERROR - Fatal exception! joblib.externals.loky.process_executor._RemoteTraceback: """ Traceback (most recent call last):   File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 490, in _process_worker     r = call_item()         ^^^^^^^^^^^   File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__     return self.fn(*self.args, **self.kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 607, in __call__     return [func(*args, **kwargs) for func, args, kwargs in self.items]             ^^^^^^^^^^^^^^^^^^^^^   File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 32, in __call__     return self._obj(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt_optimizer.py", line 267, in generate_optimizer_wrapped     return self.generate_optimizer(params_dict)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt_optimizer.py", line 330, in generate_optimizer     bt_results = self.backtesting.backtest(                  ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/freqtrade/freqtrade/optimize/backtesting.py", line 1680, in backtest     data: dict = self._get_ohlcv_as_lists(processed)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/freqtrade/freqtrade/optimize/backtesting.py", line 468, in _get_ohlcv_as_lists     df_analyzed = self.strategy.ft_advise_signals(pair_data, {"pair": pair})                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/freqtrade/freqtrade/strategy/interface.py", line 1762, in ft_advise_signals     dataframe = self.advise_entry(dataframe, metadata)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/freqtrade/freqtrade/strategy/interface.py", line 1825, in advise_entry     if "enter_long" not in df.columns:                            ^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'columns' """
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 47, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 111, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt.py", line 295, in start
    f_val = self.run_optimizer_parallel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt.py", line 160, in run_optimizer_parallel
    return parallel(optimizer_wrapper(v) for v in asked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 758, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 773, in _return_or_raise
    raise self._result
AttributeError: 'NoneType' object has no attribute 'columns'

PS C:\dokeri\freqtrade-stable>