Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0/100   0% • 0:00:06 • -:--:-- 2025-06-11 21:38:18,163 - freqtrade - ERROR - Fatal exception! joblib.externals.loky.process_executor._RemoteTraceback: """ Traceback (most recent call last):   File "/home/ftuser/.local/lib/python3.13/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc     return self._engine.get_loc(casted_key)            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^   File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc   File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc   File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item   File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'dc_upper'
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py", line 490, in _process_worker
    r = call_item()
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 607, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
            ~~~~^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 32, in __call__
    return self._obj(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt_optimizer.py", line 267, in generate_optimizer_wrapped
    return self.generate_optimizer(params_dict)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt_optimizer.py", line 330, in generate_optimizer
    bt_results = self.backtesting.backtest(
        processed=processed, start_date=self.min_date, end_date=self.max_date
    )
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1680, in backtest
    data: dict = self._get_ohlcv_as_lists(processed)
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 468, in _get_ohlcv_as_lists
    df_analyzed = self.strategy.ft_advise_signals(pair_data, {"pair": pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 1762, in ft_advise_signals
    dataframe = self.advise_entry(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1824, in advise_entry
    df = self.populate_entry_trend(dataframe, metadata)
  File "/freqtrade/user_data/strategies/JohnWickSniperStrategy.py", line 164, in populate_entry_trend
    (dataframe['close'] > dataframe['dc_upper'])
                          ~~~~~~~~~^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ftuser/.local/lib/python3.13/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'dc_upper'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 47, in main
    return_code = args["func"](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 111, in start_hyperopt
    hyperopt.start()
    ~~~~~~~~~~~~~~^^
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt.py", line 295, in start
    f_val = self.run_optimizer_parallel(
        parallel,
        [asked1.params for asked1 in asked],
    )
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt.py", line 160, in run_optimizer_parallel
    return parallel(optimizer_wrapper(v) for v in asked)
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 758, in get_result
    return self._return_or_raise()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 773, in _return_or_raise
    raise self._result
KeyError: 'dc_upper'